version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sa12345678"
      POSTGRES_DB: "BancoDigital"
    networks:
      - dockerapi-dev